all: Train_TransC Test_TransC
Train_TransC: Train_TransC.cpp
	g++ Train_TransC.cpp -o Train_TransC -O2
Test_TransC: Test_TransC.cpp
	g++ Test_TransC.cpp -o Test_TransC -O2
clean:
	rm -rf Train_TransC Test_TransC